version: '3.2'
#
### Services
#
services:
#
# Prometheus
#
   prometheus:
    image: prom/prometheus:latest
    restart: always
    container_name: prometheus
    ports:
    - 9090:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
    - cadvisor
    - node_exporter

# CAdvisor
#
   cadvisor:
    image: google/cadvisor:latest
    restart: always
    container_name: cadvisor
    ports:
    - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    cap_add: 
    - SYS_TIME
    depends_on:
    - redis
#
# Redis
#
   redis:
    image: redis:latest
    restart: always
    container_name: redis
    ports:
    - 6379:6379
# 
# Node_exporter
#
   node_exporter: 
    image: quay.io/prometheus/node-exporter
    container_name: node_exporter
    pid: "host"
    volumes: 
    - /:/host:ro,rslave
    ports: 
    - 9100:9100
    cap_add: 
    - SYS_TIME
